// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BrowserDescriptionSearchResult
    {
        /// <summary>
        /// Initializes a new instance of the BrowserDescriptionSearchResult
        /// class.
        /// </summary>
        public BrowserDescriptionSearchResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BrowserDescriptionSearchResult
        /// class.
        /// </summary>
        public BrowserDescriptionSearchResult(bool? active = default(bool?), ConceptMini concept = default(ConceptMini), string languageCode = default(string), string module = default(string), string term = default(string))
        {
            Active = active;
            Concept = concept;
            LanguageCode = languageCode;
            Module = module;
            Term = term;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "concept")]
        public ConceptMini Concept { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languageCode")]
        public string LanguageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "module")]
        public string Module { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

    }
}
