// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BuildVersion
    {
        /// <summary>
        /// Initializes a new instance of the BuildVersion class.
        /// </summary>
        public BuildVersion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BuildVersion class.
        /// </summary>
        public BuildVersion(string time = default(string), string version = default(string))
        {
            Time = time;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "time")]
        public string Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
