// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CodeSystem
    {
        /// <summary>
        /// Initializes a new instance of the CodeSystem class.
        /// </summary>
        public CodeSystem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CodeSystem class.
        /// </summary>
        public CodeSystem(string branchPath = default(string), string countryCode = default(string), bool? dailyBuildAvailable = default(bool?), string defaultLanguageCode = default(string), IList<string> defaultLanguageReferenceSets = default(IList<string>), int? dependantVersionEffectiveTime = default(int?), IDictionary<string, string> languages = default(IDictionary<string, string>), CodeSystemVersion latestVersion = default(CodeSystemVersion), object modules = default(object), string name = default(string), string shortName = default(string))
        {
            BranchPath = branchPath;
            CountryCode = countryCode;
            DailyBuildAvailable = dailyBuildAvailable;
            DefaultLanguageCode = defaultLanguageCode;
            DefaultLanguageReferenceSets = defaultLanguageReferenceSets;
            DependantVersionEffectiveTime = dependantVersionEffectiveTime;
            Languages = languages;
            LatestVersion = latestVersion;
            Modules = modules;
            Name = name;
            ShortName = shortName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branchPath")]
        public string BranchPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dailyBuildAvailable")]
        public bool? DailyBuildAvailable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultLanguageCode")]
        public string DefaultLanguageCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultLanguageReferenceSets")]
        public IList<string> DefaultLanguageReferenceSets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dependantVersionEffectiveTime")]
        public int? DependantVersionEffectiveTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "languages")]
        public IDictionary<string, string> Languages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "latestVersion")]
        public CodeSystemVersion LatestVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "modules")]
        public object Modules { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; set; }

    }
}
