// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CodeSystemVersion
    {
        /// <summary>
        /// Initializes a new instance of the CodeSystemVersion class.
        /// </summary>
        public CodeSystemVersion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CodeSystemVersion class.
        /// </summary>
        public CodeSystemVersion(string branchPath = default(string), string description = default(string), int? effectiveDate = default(int?), System.DateTime? importDate = default(System.DateTime?), string parentBranchPath = default(string), string shortName = default(string), string version = default(string))
        {
            BranchPath = branchPath;
            Description = description;
            EffectiveDate = effectiveDate;
            ImportDate = importDate;
            ParentBranchPath = parentBranchPath;
            ShortName = shortName;
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "branchPath")]
        public string BranchPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveDate")]
        public int? EffectiveDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "importDate")]
        public System.DateTime? ImportDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parentBranchPath")]
        public string ParentBranchPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shortName")]
        public string ShortName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string Version { get; set; }

    }
}
