// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConceptView
    {
        /// <summary>
        /// Initializes a new instance of the ConceptView class.
        /// </summary>
        public ConceptView()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConceptView class.
        /// </summary>
        public ConceptView(bool? active = default(bool?), IList<Axiom> classAxioms = default(IList<Axiom>), string conceptId = default(string), string definitionStatusId = default(string), IList<Description> descriptions = default(IList<Description>), string effectiveTime = default(string), TermLangPojo fsn = default(TermLangPojo), IList<Axiom> gciAxioms = default(IList<Axiom>), string moduleId = default(string), TermLangPojo pt = default(TermLangPojo), IList<Relationship> relationships = default(IList<Relationship>))
        {
            Active = active;
            ClassAxioms = classAxioms;
            ConceptId = conceptId;
            DefinitionStatusId = definitionStatusId;
            Descriptions = descriptions;
            EffectiveTime = effectiveTime;
            Fsn = fsn;
            GciAxioms = gciAxioms;
            ModuleId = moduleId;
            Pt = pt;
            Relationships = relationships;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "classAxioms")]
        public IList<Axiom> ClassAxioms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conceptId")]
        public string ConceptId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitionStatusId")]
        public string DefinitionStatusId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descriptions")]
        public IList<Description> Descriptions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveTime")]
        public string EffectiveTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fsn")]
        public TermLangPojo Fsn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gciAxioms")]
        public IList<Axiom> GciAxioms { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "moduleId")]
        public string ModuleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pt")]
        public TermLangPojo Pt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relationships")]
        public IList<Relationship> Relationships { get; set; }

    }
}
