// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConceptMini
    {
        /// <summary>
        /// Initializes a new instance of the ConceptMini class.
        /// </summary>
        public ConceptMini()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConceptMini class.
        /// </summary>
        public ConceptMini(bool? active = default(bool?), string conceptId = default(string), string definitionStatus = default(string), long? descendantCount = default(long?), string effectiveTime = default(string), TermLangPojo fsn = default(TermLangPojo), string id = default(string), bool? isLeafInferred = default(bool?), bool? isLeafStated = default(bool?), string moduleId = default(string), TermLangPojo pt = default(TermLangPojo))
        {
            Active = active;
            ConceptId = conceptId;
            DefinitionStatus = definitionStatus;
            DescendantCount = descendantCount;
            EffectiveTime = effectiveTime;
            Fsn = fsn;
            Id = id;
            IsLeafInferred = isLeafInferred;
            IsLeafStated = isLeafStated;
            ModuleId = moduleId;
            Pt = pt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conceptId")]
        public string ConceptId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "definitionStatus")]
        public string DefinitionStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "descendantCount")]
        public long? DescendantCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "effectiveTime")]
        public string EffectiveTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fsn")]
        public TermLangPojo Fsn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isLeafInferred")]
        public bool? IsLeafInferred { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isLeafStated")]
        public bool? IsLeafStated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "moduleId")]
        public string ModuleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pt")]
        public TermLangPojo Pt { get; set; }

    }
}
