// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConceptReferencesResult
    {
        /// <summary>
        /// Initializes a new instance of the ConceptReferencesResult class.
        /// </summary>
        public ConceptReferencesResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConceptReferencesResult class.
        /// </summary>
        public ConceptReferencesResult(long? limit = default(long?), long? offset = default(long?), object referencesByType = default(object), long? total = default(long?))
        {
            Limit = limit;
            Offset = offset;
            ReferencesByType = referencesByType;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "limit")]
        public long? Limit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offset")]
        public long? Offset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencesByType")]
        public object ReferencesByType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public long? Total { get; set; }

    }
}
