// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ConceptMicro
    {
        /// <summary>
        /// Initializes a new instance of the ConceptMicro class.
        /// </summary>
        public ConceptMicro()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConceptMicro class.
        /// </summary>
        public ConceptMicro(string id = default(string), bool? primitive = default(bool?), string term = default(string))
        {
            Id = id;
            Primitive = primitive;
            Term = term;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primitive")]
        public bool? Primitive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

    }
}
