// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExpressionStringPojo
    {
        /// <summary>
        /// Initializes a new instance of the ExpressionStringPojo class.
        /// </summary>
        public ExpressionStringPojo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExpressionStringPojo class.
        /// </summary>
        public ExpressionStringPojo(string expression = default(string))
        {
            Expression = expression;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expression")]
        public string Expression { get; set; }

    }
}
