// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExpressionAttribute
    {
        /// <summary>
        /// Initializes a new instance of the ExpressionAttribute class.
        /// </summary>
        public ExpressionAttribute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExpressionAttribute class.
        /// </summary>
        public ExpressionAttribute(ConceptMicro type = default(ConceptMicro), ConceptMicro value = default(ConceptMicro))
        {
            Type = type;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public ConceptMicro Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public ConceptMicro Value { get; set; }

    }
}
