// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InactivationTypeAndConceptIdList
    {
        /// <summary>
        /// Initializes a new instance of the InactivationTypeAndConceptIdList
        /// class.
        /// </summary>
        public InactivationTypeAndConceptIdList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InactivationTypeAndConceptIdList
        /// class.
        /// </summary>
        public InactivationTypeAndConceptIdList(object conceptIds = default(object), ConceptMini inactivationIndicator = default(ConceptMini))
        {
            ConceptIds = conceptIds;
            InactivationIndicator = inactivationIndicator;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "conceptIds")]
        public object ConceptIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inactivationIndicator")]
        public ConceptMini InactivationIndicator { get; set; }

    }
}
