// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class InboundRelationshipsResult
    {
        /// <summary>
        /// Initializes a new instance of the InboundRelationshipsResult class.
        /// </summary>
        public InboundRelationshipsResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InboundRelationshipsResult class.
        /// </summary>
        public InboundRelationshipsResult(IList<Relationship> inboundRelationships = default(IList<Relationship>), int? total = default(int?))
        {
            InboundRelationships = inboundRelationships;
            Total = total;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inboundRelationships")]
        public IList<Relationship> InboundRelationships { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
