// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RefSetMemberPageWithBucketAggregationsReferenceSetMember
    {
        /// <summary>
        /// Initializes a new instance of the
        /// RefSetMemberPageWithBucketAggregationsReferenceSetMember class.
        /// </summary>
        public RefSetMemberPageWithBucketAggregationsReferenceSetMember()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// RefSetMemberPageWithBucketAggregationsReferenceSetMember class.
        /// </summary>
        public RefSetMemberPageWithBucketAggregationsReferenceSetMember(bool? first = default(bool?), IList<ReferenceSetMember> items = default(IList<ReferenceSetMember>), bool? last = default(bool?), IDictionary<string, long?> memberCountsByReferenceSet = default(IDictionary<string, long?>), int? number = default(int?), int? numberOfElements = default(int?), IDictionary<string, ConceptMini> referenceSets = default(IDictionary<string, ConceptMini>), int? size = default(int?), long? totalElements = default(long?), int? totalPages = default(int?))
        {
            First = first;
            Items = items;
            Last = last;
            MemberCountsByReferenceSet = memberCountsByReferenceSet;
            Number = number;
            NumberOfElements = numberOfElements;
            ReferenceSets = referenceSets;
            Size = size;
            TotalElements = totalElements;
            TotalPages = totalPages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first")]
        public bool? First { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<ReferenceSetMember> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last")]
        public bool? Last { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "memberCountsByReferenceSet")]
        public IDictionary<string, long?> MemberCountsByReferenceSet { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public int? Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numberOfElements")]
        public int? NumberOfElements { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceSets")]
        public IDictionary<string, ConceptMini> ReferenceSets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalElements")]
        public long? TotalElements { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalPages")]
        public int? TotalPages { get; set; }

    }
}
