// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TermLangPojo
    {
        /// <summary>
        /// Initializes a new instance of the TermLangPojo class.
        /// </summary>
        public TermLangPojo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TermLangPojo class.
        /// </summary>
        public TermLangPojo(string lang = default(string), string term = default(string))
        {
            Lang = lang;
            Term = term;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lang")]
        public string Lang { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "term")]
        public string Term { get; set; }

    }
}
