// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TypeReferences
    {
        /// <summary>
        /// Initializes a new instance of the TypeReferences class.
        /// </summary>
        public TypeReferences()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TypeReferences class.
        /// </summary>
        public TypeReferences(ConceptMini referenceType = default(ConceptMini), object referencingConcepts = default(object))
        {
            ReferenceType = referenceType;
            ReferencingConcepts = referencingConcepts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referenceType")]
        public ConceptMini ReferenceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "referencingConcepts")]
        public object ReferencingConcepts { get; set; }

    }
}
