// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for FindDescriptionsUsingGET.
    /// </summary>
    public static partial class FindDescriptionsUsingGETExtensions
    {
            /// <summary>
            /// Search descriptions across multiple Code Systems.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='term'>
            /// term
            /// </param>
            /// <param name='acceptLanguage'>
            /// Accept-Language
            /// </param>
            /// <param name='active'>
            /// active
            /// </param>
            /// <param name='module'>
            /// module
            /// </param>
            /// <param name='language'>
            /// Set of two character language codes to match. The English language code
            /// 'en' will not be added automatically, in contrast to the Accept-Language
            /// header which always includes it. Accept-Language header still controls
            /// result FSN and PT language selection.
            /// </param>
            /// <param name='type'>
            /// Set of description types to include. Pick descendants of
            /// '900000000000446008 | Description type (core metadata concept) |'.
            /// </param>
            /// <param name='conceptActive'>
            /// conceptActive
            /// </param>
            /// <param name='contentScope'>
            /// contentScope. Possible values include: 'ALL_PUBLISHED_CONTENT'
            /// </param>
            /// <param name='offset'>
            /// offset
            /// </param>
            /// <param name='limit'>
            /// limit
            /// </param>
            public static ItemsPageBrowserDescriptionSearchResult One(this IFindDescriptionsUsingGET operations, string term, string acceptLanguage, bool? active = default(bool?), string module = default(string), IList<string> language = default(IList<string>), IList<long?> type = default(IList<long?>), bool? conceptActive = default(bool?), string contentScope = default(string), int? offset = 0, int? limit = 50)
            {
                return operations.OneAsync(term, acceptLanguage, active, module, language, type, conceptActive, contentScope, offset, limit).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Search descriptions across multiple Code Systems.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='term'>
            /// term
            /// </param>
            /// <param name='acceptLanguage'>
            /// Accept-Language
            /// </param>
            /// <param name='active'>
            /// active
            /// </param>
            /// <param name='module'>
            /// module
            /// </param>
            /// <param name='language'>
            /// Set of two character language codes to match. The English language code
            /// 'en' will not be added automatically, in contrast to the Accept-Language
            /// header which always includes it. Accept-Language header still controls
            /// result FSN and PT language selection.
            /// </param>
            /// <param name='type'>
            /// Set of description types to include. Pick descendants of
            /// '900000000000446008 | Description type (core metadata concept) |'.
            /// </param>
            /// <param name='conceptActive'>
            /// conceptActive
            /// </param>
            /// <param name='contentScope'>
            /// contentScope. Possible values include: 'ALL_PUBLISHED_CONTENT'
            /// </param>
            /// <param name='offset'>
            /// offset
            /// </param>
            /// <param name='limit'>
            /// limit
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ItemsPageBrowserDescriptionSearchResult> OneAsync(this IFindDescriptionsUsingGET operations, string term, string acceptLanguage, bool? active = default(bool?), string module = default(string), IList<string> language = default(IList<string>), IList<long?> type = default(IList<long?>), bool? conceptActive = default(bool?), string contentScope = default(string), int? offset = 0, int? limit = 50, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.OneWithHttpMessagesAsync(term, acceptLanguage, active, module, language, type, conceptActive, contentScope, offset, limit, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Search descriptions across multiple Code Systems.
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='term'>
            /// term
            /// </param>
            /// <param name='acceptLanguage'>
            /// Accept-Language
            /// </param>
            /// <param name='active'>
            /// active
            /// </param>
            /// <param name='module'>
            /// module
            /// </param>
            /// <param name='language'>
            /// Set of two character language codes to match. The English language code
            /// 'en' will not be added automatically, in contrast to the Accept-Language
            /// header which always includes it. Accept-Language header still controls
            /// result FSN and PT language selection.
            /// </param>
            /// <param name='type'>
            /// Set of description types to include. Pick descendants of
            /// '900000000000446008 | Description type (core metadata concept) |'.
            /// </param>
            /// <param name='conceptActive'>
            /// conceptActive
            /// </param>
            /// <param name='contentScope'>
            /// contentScope. Possible values include: 'ALL_PUBLISHED_CONTENT'
            /// </param>
            /// <param name='offset'>
            /// offset
            /// </param>
            /// <param name='limit'>
            /// limit
            /// </param>
            /// <param name='customHeaders'>
            /// Headers that will be added to request.
            /// </param>
            public static HttpOperationResponse<ItemsPageBrowserDescriptionSearchResult> OneWithHttpMessages(this IFindDescriptionsUsingGET operations, string term, string acceptLanguage, bool? active = default(bool?), string module = default(string), IList<string> language = default(IList<string>), IList<long?> type = default(IList<long?>), bool? conceptActive = default(bool?), string contentScope = default(string), int? offset = 0, int? limit = 50, Dictionary<string, List<string>> customHeaders = null)
            {
                return operations.OneWithHttpMessagesAsync(term, acceptLanguage, active, module, language, type, conceptActive, contentScope, offset, limit, customHeaders, CancellationToken.None).ConfigureAwait(false).GetAwaiter().GetResult();
            }

    }
}
