// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// FindConceptsUsingGET operations.
    /// </summary>
    public partial interface IFindConceptsUsingGET
    {
        /// <summary>
        /// Search concepts across multiple Code Systems.
        /// </summary>
        /// <param name='acceptLanguage'>
        /// Accept-Language
        /// </param>
        /// <param name='conceptIds'>
        /// conceptIds
        /// </param>
        /// <param name='active'>
        /// active
        /// </param>
        /// <param name='offset'>
        /// offset
        /// </param>
        /// <param name='limit'>
        /// limit
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<ItemsPageConceptMini>> OneWithHttpMessagesAsync(string acceptLanguage, IList<string> conceptIds = default(IList<string>), bool? active = default(bool?), int? offset = 0, int? limit = 50, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
