// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SnomedApi
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// FindDescriptionsUsingGET operations.
    /// </summary>
    public partial interface IFindDescriptionsUsingGET
    {
        /// <summary>
        /// Search descriptions across multiple Code Systems.
        /// </summary>
        /// <param name='term'>
        /// term
        /// </param>
        /// <param name='acceptLanguage'>
        /// Accept-Language
        /// </param>
        /// <param name='active'>
        /// active
        /// </param>
        /// <param name='module'>
        /// module
        /// </param>
        /// <param name='language'>
        /// Set of two character language codes to match. The English language
        /// code 'en' will not be added automatically, in contrast to the
        /// Accept-Language header which always includes it. Accept-Language
        /// header still controls result FSN and PT language selection.
        /// </param>
        /// <param name='type'>
        /// Set of description types to include. Pick descendants of
        /// '900000000000446008 | Description type (core metadata concept) |'.
        /// </param>
        /// <param name='conceptActive'>
        /// conceptActive
        /// </param>
        /// <param name='contentScope'>
        /// contentScope. Possible values include: 'ALL_PUBLISHED_CONTENT'
        /// </param>
        /// <param name='offset'>
        /// offset
        /// </param>
        /// <param name='limit'>
        /// limit
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<ItemsPageBrowserDescriptionSearchResult>> OneWithHttpMessagesAsync(string term, string acceptLanguage, bool? active = default(bool?), string module = default(string), IList<string> language = default(IList<string>), IList<long?> type = default(IList<long?>), bool? conceptActive = default(bool?), string contentScope = default(string), int? offset = 0, int? limit = 50, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
